# See https://docs.flagsmith.com/deployment/docker for more information on running Flagsmith in Docker
# This will docker-compose file will run the entire Flagsmith Platform in Docker
# Uncomment and configure InfluxDB lines below (not neccesary but adds some functionality that requires InfluxDB)

version: '3'
services:
    db:
        image: postgres:11.12-alpine
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: flagsmith
        container_name: flagsmith_postgres

    api:
        image: flagsmith/flagsmith:latest
        environment:
            DJANGO_ALLOWED_HOSTS: '*' # Change this in production
            DATABASE_URL: postgresql://postgres:password@db:5432/flagsmith
            DISABLE_INFLUXDB_FEATURES: 1 # Comment out to enable InfluxDB
            # INFLUXDB_URL: http://influxdb:8086
            # INFLUXDB_BUCKET: flagsmith_api
            # INFLUXDB_ORG: # Add your influx org id here - see readme.md
            # INFLUXDB_TOKEN: # Add your influx token here - see readme.md
        ports:
            - '8000:8000'
        depends_on:
            - db
        links:
            - db:db
            # - influxdb:influxdb
        container_name: flagsmith

    # InfluxDB requires additional setup - please see https://docs.flagsmith.com/deployment-overview/#influxdb
    # Note that InfluxDB is optional, but enabling it will provide additional functionality to the Flagsmith platform
    # influxdb:
    #   image: quay.io/influxdb/influxdb:v2.0.3
    #   container_name: flagsmith_influxdb
    #   ports:
    #     - "8086:8086"
